### ISSUE TITLE
Cannot find module './scripts'

### ISSUE THREAD

**Issue by rossdargan** [vangie/travis-ci-webhook#3]
Hi

I'm getting the following error now :)

> $ node index.js
> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module './scripts'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/src/app/index.js:20:15)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
> error Command failed with exit code 1.

This is my docker compose file

```
 travis:
  image: "vangie/travis-ci-webhook"
  container_name: travis
  restart: always
  volumes:
   - "/travis/scripts:/usr/src/app/scripts"
   - "/travis/env.override:/usr/src/app/.env.override"
  ports:
   - "7777:7777"
```
